### ISSUE TITLE
Write November impact email series

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#570] opened 2015-10-16 21:31 UTC
In mid-November, we'll send our big list a series of two emails to outline the impact of our work in 2014. In addition to updating our supporters about our work, it primes them for the EOY asks that will roll out in December.

This will be sent on Exact Target using our standard, mobile-ready template. 

MVP is text only. Nice-to-haves are photos or graphic callouts.

#### Email 1: All the Things! 
Content: Highlights all the wonderful things Mozilla has done in 2014. Content can be pulled from board presentation. P.S. can be a light-touch donate ask that says "we're going to kick off our EOY in December. If you donate now, we'll exclude you from our asks"
Send date: Monday Nov 16

#### Email 2: Suchita’s story 
Content: A personal, individual story (Suchita). [This is written already] (https://github.com/MozillaFoundation/2015-fundraising/issues/30), and just needs to be tweaked to make sense as the 2nd email of this series. P.S. Can be a light-touch donate ask. Would be great to include a photo of Suchita.
Send date: Thursday Nov 19

Heads up @adamlofting that we'd love to segment these sends by donor/non-donor to monitor the open and CTR.

**Comment by edrushka** [comment] 2015-10-16 21:33
Assigning this to @valianttry to write, but would love @KevZawacki's review. Accordingly, I've made the deadline Oct 30 so Kevin has time to look it over before MozFest.

**Comment by valianttry** [comment] 2015-10-16 23:25
Actually, if @KevZawacki wants to take a crack while i'm out next week please do! Otherwise i'll try to get to this asap when i come back.

**Comment by valianttry** [comment] 2015-10-17 00:21
I'm going to dig out a few good examples of these kinds of emails to drop here in the ticket (we haven't done a really good one, honestly, since I've been here). Here's one from Fair Agenda, a great org out of Australia:

Andrea,

A little over a year ago, Fair Agenda did not even exist.

Today, thanks to your support, it's now a (still small) but mighty force of passionate volunteers and one part-time staff member who have pulled off high profile media, important campaign wins, awareness raising and strategic interventions in state elections on a shoestring budget and in a short amount of time.  

It's no overstatement to say that our campaigns this year - and the wins that our community has achieved - could not have happened were it not for you.

Here are 5 highlights from our year together:

1. You helped to found an organisation! In March this year, Fair Agenda launched its first campaigns, and started working to help bring Australians together to have maximum impact at critical moments, and drive change on the local, state and federal stage. 

2. Together, we got the issues you care about on the agenda and in front of thousands of voters in key election races, during the Victorian state election and WA senate by-election. 

3. We helped put women’s representation on the agenda with our campaigns around women in cabinet and the Just for Laughs festival. 

4. We backed family violence experts – coming together in critical moments to demonstrate voter support for the changes front line support workers and policy experts say are required to protect women and children, including: death review processes, specialised services, and responsible reporting by the media.

5. We held big companies to account for the messages they sent about women and girls – pushing Myer to commit not to buy more of the stick thin Winx dolls, and helping put media pressure on Libra after their infamous ‘absorbs way more than you ever did in maths class’ advert.
Together, we're only getting stronger -- and we need your help to make sure our impact, size, power and income is doubled in 2015. This year, 80 members chipped in $7,364 to support our work fighting for equality. If just 100 of us commit right now to spend $25 a month in 2015 supporting this work, it will help ensure our community has the resources to dedicate a full time staff member to drive more campaigns like this, at critical moments, on the issues we all care about. 

Can you help make that happen by becoming a Fair Agenda Champion and committing right now to give just $25 per month for 2015?

http://fairagenda.nationbuilder.com/monthly_donor

The Fair Agenda story so far is one of what a group of dedicated community members can achieve if they have the will, and there's a way. 

I'm so proud of everything our small group of passionate supporters, campaigners, volunteers and advisors have achieved on so little. It's quite amazing, really. But I'm also confident that if we all dig deep now we can be bigger, better, louder and more hard-hitting in 2015, and bring closer our shared vision for a more fair and equal Australia.

Together, we can be fierce, powerful and unforgettable.

Are you in?

Renee for the entire Fair Agenda team.

PS - The seed of an idea that led to Fair Agenda came on the heels of quite a year, one that saw an ousted female Prime Minister who was subject to unprecedented level of gendered attacks, a new Prime Minster who appointed just one female to his first Cabinet, and a slew of bad news when it came to equal pay, representation on boards, domestic violence and reproductive rights. 

At the end of 2014, we're still up against similar battles. In fact, before Christmas, Tony Abbott said that the top achievement in his role as the "Prime Minister for Women" was getting rid of the price on carbon because "as many of us know, women are particularly focused on the household budget…" 

Let’s imagine a 2015 in which women are not only not "focused on the household budget”, but are also on equal pay, earning as much superannuation as their male counterparts, and helping drive the decisions that shape our communities - as equal members of cabinet and of boards. Let's take it even further - and imagine a future in which women feel safer in their homes and walking down the streets because we’ve fought for changes that protect our bodies, and our rights.

It's not an unrealistic dream. But we're not there yet; and that's why Fair Agenda was created. Can you help support our work to help make it a reality? 

Become a regular supporter here, or make a once off end of year donation here. 

Thanks for all you've done this year. Here's to a bigger and better 2015.

Fair Agenda · Australia 
This email was sent to andrealw@gmail.com. To stop receiving emails, click here. 
You can also keep up with Fair Agenda on Twitter or Facebook.

Created with NationBuilder, the essential toolkit for leaders

**Comment by valianttry** [comment] 2015-10-17 00:25
MomsRising kept theirs short, but linked to a blog post (http://www.momsrising.org/blog/26-inspiring-victories-you-made-possible-in-2014 -- A blog post like this would be easy to do):

![the_good_you ve_done_in_2014_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/10555850/c0dade00-742a-11e5-9348-26f93d154bc9.png)

**Comment by valianttry** [comment] 2015-10-17 00:26
Plan International USA's effort looks dated, and is a newsletter, but the content ideas are pretty good. I particularly like "your impact in 11 photos":

![a_few_ways_we_impacted_children_s_lives_in_2014_-_andrealw_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/9830371/10555869/03648d0c-742b-11e5-8af9-21d0d6db598f.png)

**Comment by valianttry** [comment] 2015-10-17 00:32
Claire McCaskill sends good emails for a Missouri Senator:

![look_at_all_we_ve_accomplished_-_andrealw_gmail_com_-_gmail_and_inbox__8_687__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/10555933/ee3f1ea0-742b-11e5-9612-674791d594a3.png)

**Comment by KevZawacki** [comment] 2015-10-19 14:43
@edrushka @valianttry I can add to my to-do list, but with MozFest and the annual report, I likely won't be able to create that first draft. However, happy to review and revise as needed!

**Comment by edrushka** [comment] 2015-10-19 15:20
Thanks @KevZawacki - I forgot about the annual report! I may be able to take an initial crack at it as well.

**Comment by edrushka** [comment] 2015-10-21 20:02
@KevZawacki can you please share State of Mozilla draft points when they are ready? This will be useful for Email 1.

**Comment by edrushka** [comment] 2015-10-28 19:57
Here's the top line "what we did in 2014" from the draft State of Mozilla:

*In 2014, we built and improved products like the Firefox browser, Firefox OS, and our Content Services offerings. We fostered educational programs and tools like Hive Learning Networks, Mozilla Clubs, and Webmaker for Android. We brought together diverse leaders through the Mozilla Festival, Mozilla Developer Network, Mozilla Science Lab and the OpenNews journalism initiative. And we launched the Open Web Fellows program, a global initiative to develop leaders capable of defending the Web.*

There may be an additional point on launching Cyber Security Delphi, a comprehensive research project to better understand security threats on the Internet, but we need confirmation before we use that as a talking point.

**Comment by valianttry** [comment] 2015-11-10 04:37
I'm starting a draft here:
https://docs.google.com/document/d/153pZQZEZnQdsL2xWxxhICe-6IYLgMqAfGZ6oEu5pr60/edit

**Comment by valianttry** [comment] 2015-11-11 06:19
OK, given the timing, I propose we slim this Impact series from 2 emails to 1 email. I wrote a draft of an "all the things" email here: https://docs.google.com/document/d/153pZQZEZnQdsL2xWxxhICe-6IYLgMqAfGZ6oEu5pr60/edit  @edrushka do you want to take a first pass, then @KevZawacki ? Or Kevin first? Depends on who emerges from the MozFest haze first.... :smile: 

A lot of the list was built this year on advocacy campaigns. Given the volume of advocacy emails sent this year I figured it was best to lean heavily on the "advocacy" victories + web literacy. It will likely catch the most honey.

If we want to draft a separate, additional email about Suchita based on @KevZawacki 's good work we can -- but we'll have to slate it in between Nov 19 and Dec 4.

**Comment by KevZawacki** [comment] 2015-11-11 14:50
@valianttry Reviewing now!

**Comment by edrushka** [comment] 2015-11-12 23:25
I've reviewed. @valianttry I suggest you revise the web lit stuff before Mark reviews. I'm almost certain he'll want that modified.

**Comment by valianttry** [comment] 2015-11-19 03:45
I think it would be a real slog to try to send a 2nd email. In addition -- the calendar is getting crowded with the MLN newsletter and the Gear Store email. I say scrap #2.

The first email got shipped today to Erica Sagrans.  Here is the final copy after Mark's edits and another copy edit review from Kevin:
https://docs.google.com/document/d/153pZQZEZnQdsL2xWxxhICe-6IYLgMqAfGZ6oEu5pr60/edit

I am trying to figure out when  Erica will be able to get it set this up in Exact Target. Closing this bug though, thanks everyone!

**Closed** 2015-11-19 03:47 UTC
Labels: copy, P1
