### ISSUE TITLE
Make sure Stripe transaction triggers an email receipt

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#360] opened 2015-09-03 14:31 UTC
It doesn't do this by default, so let's make sure we're triggering the basic level of reciept as a minimum.
https://support.stripe.com/questions/email-receipts

After this we can work on design enhancements.

**Comment by ScottDowne** [comment] 2015-09-23 23:15
It can, and it's easy, but it's in English only...

**Comment by ScottDowne** [comment] 2015-09-24 15:00
We're going with English for now as a P1 solution.

Later we'll listen to Stripe's webhook and send out our own localized email with info on how to update a subscription..

**Comment by ScottDowne** [comment] 2015-09-24 18:20
I set this up in the test account, but it only actually does anything for real Stripe accounts, so this is blocked but I have a good idea how to do this.

The setting works for both recurring (each billing) and one time.

Keeping this open to test once we have a real Stripe account.

**Comment by valianttry** [comment] 2015-09-28 21:20
@ScottDowne we actually do have DE translated version of this email auto-reply. Is there a reason we won't send an automated receipt in DE for donors who give through the DE form? See Pontoon here: https://pontoon.mozilla.org/de/fundraising/Emails/

**Comment by jbuck** [comment] 2015-09-28 21:49
@valianttry I think it was a question of implementation time, mostly.

**Comment by ScottDowne** [comment] 2015-09-28 23:38
@valianttry @jbuck yeah, so using Stripe to send out the email is the easy solution, but it only gets us English which is not great.

If we setup our own email sending thing, and linked that with Stripe, we could send out whatever email in whatever language, but would require more work. jbuck would have a better idea for how long that would take as I have never done something like that.

I would need to know the priority on something like this and compare that with how long jbuck would guess it would take.

**Comment by ScottDowne** [comment] 2015-11-04 18:22
Duplicate of #661

**Closed** 2015-11-04 18:22 UTC
Labels: engineering, P1
