### ISSUE TITLE
Design a snippet Thank You message for 4 locales

### ISSUE THREAD

**Issue by edrushka** [mozilla/donate.mozilla.org#1062] opened 2015-12-04 23:56 UTC
Jean is interested in putting the Thank You video on the snippet in January. Because it's in English only, we'll need some localized alternatives for our other main locales (FR, DE, PTBR, ES). 

Visually, this should be a pretty standard snippet. It can be Dapper Fox branded, but it's not supposed to be disruptive. For example, it could be a static or gently animated Dapper Fox icon with the standard line or two of text.

@valianttry do you have any copy suggestions we can start with? We'll have to run by Jean's team but this will allow Natalie to get going. Maybe "From all of us at Mozilla, thank you to our donors."

cc @cassiemc

**Comment by cassiemc** [comment] 2015-12-14 16:13
This seems very straightforward. Just an icon of dapper fox, and @edrushka said – with possible gentle animation to it, depending on other deadlines. Nothing special needed for the rest of the page design imo. cc @natalieworth

**Comment by edrushka** [comment] 2015-12-14 21:10
@valianttry @KevZawacki can you please finalize this copy? Thanks!

**Comment by KevZawacki** [comment] 2015-12-14 21:31
@edrushka Simple seems best for a thank you. I like your suggestion: "From all of us at Mozilla, thank you to our donors."

A couple others, if we need variation:

To our donors around the world: thank you for supporting a better Internet!

Thank you to our donors — your support helps build a better Internet!

**Comment by natalieworth** [comment] 2015-12-16 00:18
@edrushka @cassiemc @valianttry @lovegushwa I've got some draft snippet examples of the 'thank-you locale' designs. I've left the UI and current design of the firefox page the same in order to not be too disruptive with the thank you additions: https://redpen.io/p/sm23f4531a66a29a58

**Comment by edrushka** [comment] 2015-12-16 00:36
Whoooa! These are more 'spectacular' than I expected! They are great, but they still feel pretty disruptive. Some of the elements could definitely work - I'll add comments in the redpen. 

Can you draft a couple "very standard" versions like this one:
![screenshot 2015-12-15 16 27 41](https://cloud.githubusercontent.com/assets/4515662/11828465/cd1730c6-a349-11e5-9b82-9107ea131a5b.png)

**Comment by natalieworth** [comment] 2015-12-16 00:41
@edrushka For sure! I'll adjust text and images

**Comment by natalieworth** [comment] 2015-12-17 00:15
Sorry, forgot to post the link here for the newest (less disruptive) snippet updates from earlier today: https://redpen.io/p/sm23f4531a66a29a58 @edrushka @cassiemc @valianttry @lovegushwa

**Comment by edrushka** [comment] 2015-12-18 16:52
@valianttry please review

**Comment by edrushka** [comment] 2015-12-19 01:12
@natalieworth do you have enough clarity in the redpens to move forward? If not, let's address in Monday's circle up.

**Comment by natalieworth** [comment] 2015-12-19 01:16
@edrushka Monday would be great to discuss! I can gather the preferred one's together and maybe we could quickly go through them?

**Comment by edrushka** [comment] 2015-12-19 01:18
+1 we could show to Jean right after.

**Comment by edrushka** [comment] 2015-12-21 22:00
@natalieworth I have copy approved by Jean and Andrea. Please mock up your 3 designs with these 3 copy variants in a fresh redpen. Thank you!

- To our 3xx,xxx donors from over 200 countries and territories around the world — thank you for supporting Mozilla's mission!
- You made our year! Thanks to your generous donations, Mozilla can work even harder to ensure the Internet is a global public resource, open and accessible to all.
- Thank you for your generous donations to Mozilla. You made our year!

**Comment by natalieworth** [comment] 2015-12-21 22:02
Just noting that tile images are to be 64 x 64 to accommodate for retina display. Once copy and the possibility of the fox in a heart becoming a gif are confirmed with Jean, I can update the snippet options for locales. cc @valianttry @edrushka

**Comment by natalieworth** [comment] 2015-12-21 22:02
@edrushka Great, thanks! Just saw this. Was there any confirmation if an animated gif would be possibly on the fox option? I can ping Jean, but wanted to double check first.

**Comment by edrushka** [comment] 2015-12-21 22:05
Can you ping Jean? We can show her the static versions first if she wants.

**Comment by natalieworth** [comment] 2015-12-21 22:22
@edrushka Jean said all good to draft a 64 x 64 px gif in the thank-you snippet locales.

**Comment by natalieworth** [comment] 2015-12-22 18:05
Hi @edrushka @valianttry  , I've got the most recent 3 thank-you snippet versions up with the image adjusted to fit within 64 x 64px. I don't know Jean's handle on Github (so feel free to cc her on this if she has one). I'll work on the fox hat-tip gif animation this morning and upload hopefully by later today. Thanks!
1. https://redpen.io/nu8fbf61e79135db26
2. https://redpen.io/ov1c02fba53af3240f
3. https://redpen.io/rx95699683930b4399

cc @lovegushwa @cassiemc

**Comment by lovegushwa** [comment] 2015-12-22 18:08
@natalieworth looks good. I like options 1 best.

**Comment by edrushka** [comment] 2015-12-22 18:23
Thanks! I sent to Jean for her review.

**Comment by edrushka** [comment] 2015-12-22 19:46
Response from Jean: 
> The Dapper Fox heart and the normal heart will work. They will, however, be aligned to the left of the text. If we had to chose, I'd go with the Dapper Fox heart.

Can you please export those 2 files @natalieworth

**Comment by natalieworth** [comment] 2015-12-22 20:55
@edrushka Here is the link to the Illustrator file for the thank-you snippet designs (V1 and V2). I'll upload the gif here for V1 hopefully by this afternoon or tomorrow morning. I adjusted the width of the text and aligned the image to the search bar based on the feedback above for snippet UI:
https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0cE14Y216c0ROOU0/view
I'm not sure what is necessary to build in terms of exporting for the devs. @lovegushwa perhaps if you get time to review my .ai file or just ping me with instructions to export when it comes time to build?

**Comment by edrushka** [comment] 2015-12-22 22:08
This is great @natalieworth. Can I get just the static icons themselves at 64x64? Thanks!

**Comment by natalieworth** [comment] 2015-12-22 23:54
@edrushka I've exported an Illustrator file and svg's for the 2 smaller images here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NVlaUHFva2Qxckk&usp=drive_web&ddrp=1#

**Comment by jbuck** [comment] 2015-12-23 18:37
@alicoding we should put these strings in Pontoon

**Comment by alicoding** [comment] 2015-12-23 18:48
I'm going to put these up on Pontoon:

* To our {numberOfDonors} donors from over 200 countries and territories around the world — thank you for supporting Mozilla's mission!
* You made our year! Thanks to your generous donations, Mozilla can work even harder to ensure the Internet is a global public resource, open and accessible to all.
* Thank you for your generous donations to Mozilla. You made our year!

Please note that this is now locked and can't put any styling to the strings.

**Comment by jbuck** [comment] 2015-12-23 19:37
@alicoding's PR has landed in #1175 and the design is done so marking this as completed!

**Closed by jbuck** 2015-12-23 19:37 UTC
Labels: design, P1

**Comment by natalieworth** [comment] 2015-12-23 21:17
Gif options for the fox svg are up on the google drive here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0N0RMSzd1S1laWlE&usp=drive_web&ddrp=1# For the gif, I've also exported one @2x for retina display (so 128 x 128px, instead of 64px x 64px) since it's not in svg format. Let me know if these work or if we'd prefer static. 
cc @edrushka @valianttry @lovegushwa
