### ISSUE TITLE
Test: Firefox Developer Edition terminal donation form

### ISSUE THREAD

**Issue by adamlofting** [mozilla/donate.mozilla.org#194] opened 2015-08-06 18:52 UTC
![terminal](https://cloud.githubusercontent.com/assets/1901816/9120487/5b240202-3c31-11e5-8ce5-99b1cacb01ed.jpg)

```bash
>$ Hello there! We know you love Firefox...
```

**Comment by adamlofting** [comment] 2015-10-23 14:18
@edrushka @valianttry 

I personally love this idea. But, do you have the capacity, and does it fit in the priority list, to manage the up front creative part of this, and the engagement with dev edition team etc?

If not, we can move this ticket to the Bluesky milestone for future reference.

**Comment by edrushka** [comment] 2015-10-23 20:32
Definitely not in scope anytime soon.

**Comment by ScottDowne** [comment] 2016-10-18 18:22
Closing this as a dupe of https://github.com/MozillaFoundation/Advocacy/issues/392

**Closed by ScottDowne** 2016-10-18 18:22 UTC
Labels: A/B Test Proposal, Needs Prioritizing
