### ISSUE TITLE
Subject line is completely missing for recurring donation email confirmations

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate.mozilla.org#2102] opened 2018-10-28 11:45 UTC
Our subject line seems to have gone completely missing when you submit a recurring donation via Stripe.  Just confirmed it with a personal donation.  Can we please fix?

![image](https://user-images.githubusercontent.com/23637882/47615454-d6ebbd00-daa6-11e8-9b6e-a728c9ab491e.png)

**Comment by WillatMozFdn** [comment] 2018-10-28 13:57
Thanks Alan.  Here's a sample of what our donors are saying ....

![image](https://user-images.githubusercontent.com/23637882/47616794-5edac280-dab9-11e8-89c7-fc9180ac6420.png)

**Comment by WillatMozFdn** [comment] 2018-10-31 16:28
@cadecairos @alanmoo also now getting reports that these are landing in spam filters due to the lack of a subject line ... any updates?

**Comment by WillatMozFdn** [comment] 2018-10-31 18:30
Thanks Alan!  @cadecairos we think this started happening on or around October 16th, not sure if that helps.

**Comment by cadecairos** [comment] 2018-10-31 19:37
@WillatMozFdn Found the issue. when we tried to get a different subject line for recurring donations, we didn't implement it properly: https://github.com/mozilla/webmaker-mailroom/pull/70/files

**Comment by cadecairos** [comment] 2018-10-31 21:22
@WillatMozFdn I've deployed the fixed email rendering library to production, this issue _should_ be resolved, but I'll leave it open until you can confirm.

**Comment by WillatMozFdn** [comment] 2018-11-01 11:56
Thanks @alanmoo and @cadecairos ... recurring subject line is now showing up for Mozilla donations as intended; unfortunately a new problem has cropped up.  Thunderbird donations are now completely futzed, see below...  
![image](https://user-images.githubusercontent.com/23637882/47850444-2b57ab00-ddcd-11e8-88fe-d5c320ec1dbe.png)

**Comment by TheoChevalier** [comment] 2018-11-01 16:05
This one is likely on me — when Chris deployed sawmill and/or mailroom, my patches for localizing TB receipts got deployed as well, while they still haven’t been tested.
Two strings are correctly localized in French, likely because there are the two that got unchanged when I added TB content, so it seems only the new strings are missing.

@cadecairos Have you deployed webmaker-mailroom yesterday too? I’d guess so, given we can see the gettext placeables and I added them

<img width="527" alt="capture d ecran 2018-11-01 a 15 59 49" src="https://user-images.githubusercontent.com/1294206/47863522-5f43c800-ddef-11e8-83e2-6ddbc65e80bc.png">

**Comment by WillatMozFdn** [comment] 2018-11-07 20:01
Hey team, we still have the original problem -- subject line is totally missing for recurring donation confirmation emails to Mozilla, which is very bad customer service for our recurring donors, and also some of these emails are going to spam because of it.  Can we please fix this ASAP please?  @alanmoo @cadecairos

**Comment by cadecairos** [comment] 2018-11-09 21:36
@WillatMozFdn This should be fixed now, can you confirm?

**Comment by WillatMozFdn** [comment] 2018-11-09 21:43
yes, I believe it is.  If we hear of any problems with T-bird or anything else, will let you know.  Thanks!!!! @cadecairos 

![image](https://user-images.githubusercontent.com/23637882/48289766-95f88e80-e43e-11e8-8131-f334d016a131.png)

**Comment by WillatMozFdn** [comment] 2018-11-12 20:58
Hey guys, unfortunately, another problem cropped up.  Thunderbird emails are now missing their subject line. @alanmoo @cadecairos ... can you investigate, please?

![image](https://user-images.githubusercontent.com/23637882/48374748-ca18bd00-e693-11e8-85d1-785024c557e5.png)

**Comment by TheoChevalier** [comment] 2018-11-13 10:38
Damn, my bad… 
Just tested with a donation, one-time donations are not affected (as I was guessing from the code), only recurring. I think I’ve found the issue, the recurring subject line copy was missing in the JS file associated to the TB email template. This should fix it, hopefully: https://github.com/mozilla/webmaker-mailroom/pull/72

**Comment by WillatMozFdn** [comment] 2018-11-13 23:08
A couple other minor problems showing up today ... in both FR and ES ... looks like the merging of amount and transaction_id fields is failing?  These are from receipt emails sent back to us in donor care cases ... the FR one is Mozilla, the ES one, Thunderbird ...

![image](https://user-images.githubusercontent.com/23637882/48449046-f81eff80-e76e-11e8-9dbf-88b495e5e4b6.png)

![image](https://user-images.githubusercontent.com/23637882/48449068-1422a100-e76f-11e8-8b66-1366ec39cf7a.png)

@TheoChevalier can you check these out, please?  Thank you!!!

**Comment by TheoChevalier** [comment] 2018-11-14 10:22
Hm, investigating, but I’m pretty sure the ES receipt is not coming from Thunderbird, but both emails are Mozilla donations.

I think this one will be hard to debug without the ability to reproduce locally, but giving it a try

**Comment by TheoChevalier** [comment] 2018-11-14 11:22
Alright, I’ve managed to reproduce locally, and found the issue. With the amount of changes made to translations, I completely missed that variables were formatted differently than in the en-US copy exposed to localizers… Updated them all to the correct format here: https://github.com/mozilla/webmaker-mailroom/pull/73/files

Since I could test locally, I’m way more confident that everything should be back to normal now.
Sorry again for the troubles here

@cadecairos Would you mind tagging and deploying a new release?

**Comment by cadecairos** [comment] 2018-11-15 16:33
I'm deploying the fix now

**Comment by cadecairos** [comment] 2018-11-15 16:42
@WillatMozFdn @TheoChevalier It's live. can you check if things are looking fixed?

**Comment by alanmoo** [comment] 2018-11-27 17:13
I haven't heard any complaints, assuming this is fixed.  Re-open if it's not.

**Closed by alanmoo** 2018-11-27 17:13 UTC
